# Generated by Django 2.1.5 on 2019-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='User ID')),
                ('user_description', models.CharField(default='', max_length=255, verbose_name='User description')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP address')),
                ('event_time', models.DateTimeField(auto_now=True)),
                ('request_path', models.URLField(verbose_name='Request path')),
                ('event_description', models.CharField(max_length=255, verbose_name='Event description')),
            ],
        ),
    ]
