# Generated by Django 2.1.5 on 2019-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0002_auto_20190426_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(verbose_name='Event description'),
        ),
    ]
